# -*- mode: python ; coding: utf-8 -*-
import os
from pathlib import Path

# プロジェクトのルートディレクトリを取得
project_root = os.path.dirname(os.path.abspath(SPECPATH))

a = Analysis(
    ['src\\main.py'],
    pathex=['.', 'src'],
    binaries=[],
    datas=[
        ('src\\core', 'core'),
        ('src\\ui', 'ui'),
        ('src_list', 'src_list'),
        ('tools', 'tools'),
        ('config', 'config'),
        ('logs', 'logs'),
        ('temp', 'temp'),
        ('exports', 'exports'),
        ('data', 'data'),
    ],
    hiddenimports=[
        'PySide6',
        'core',
        'ui',
        'src_list',
        'src_list.core',
        'src_list.models',
        'src_list.ui',
        'core.logger',
        'core.config_manager',
        'core.constants',
        'core.database',
        'core.export_manager',
        'core.gemini_api',
        'core.video_processor',
        'ui.main_window',
        'asyncio',
        'asyncio.base_events',
        'asyncio.coroutines',
        'asyncio.events',
        'asyncio.exceptions',
        'asyncio.futures',
        'asyncio.locks',
        'asyncio.protocols',
        'asyncio.queues',
        'asyncio.runners',
        'asyncio.streams',
        'asyncio.subprocess',
        'asyncio.tasks',
        'asyncio.threads',
        'asyncio.transports',
        'asyncio.unix_events',
        'asyncio.windows_events',
        'asyncio.windows_utils',
        '_asyncio',
        '_overlapped',
        'selectors',
        'concurrent.futures',
        'concurrent.futures.thread',
        'concurrent.futures.process'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MP4toExplainText',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['ICON.ico'],
)
